services:
  orders_db:
    image: "postgres:11"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders

  orders:
    build:
      context: orders
    ports:
      - "8080:8080"
    depends_on:
      - orders_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://orders_db:5432/orders
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
